name: Create PR
on:
  pull_request:
    branches:
      - main
    types:
      [opened, reopened]
jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Create pull request
      run: |
        chmod +x ./.github/scripts/create_pr.sh
        ./.github/scripts/create_pr.sh ${{ github.head_ref }} ${{ github.event.pull_request.title }} ${{ github.event.pull_request.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
