name: Create PR
on:
  pull_request:
    branches:
      - main
    types:
      [opened, edited]
jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Create pull request
      run: |
        echo "hello world"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
