name: Create PR to hoge on main PR

on:
  pull_request:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Create new file (Example)
      run: echo "New file for hoge branch" > hoge.txt

    - name: Commit changes
      run: |
        git switch -c hoge
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Add new file to hoge branch'
        git push -u origin hoge

    - name: Create Pull Request
      run: |
        gh pr create --base main --title "new" --body "new"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}