name: Create PR to hoge on main PR

on:
  pull_request:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: run
      run: |
        ./.github/scripts/create_pr.sh ${{ github.ref_name }} ${{ github.event.pull_request.title }} ${{ github.event.pull_request.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
