name: Create PR to hoge on main PR

on:
  pull_request:
    branches:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Create new file (Example)
      run: echo "New file for hoge branch" > hoge.txt

    - name: Commit changes
      run: |
        git switch -c hoge
        git add .
        git commit -m 'Add new file to hoge branch'
        git push -u origin hoge

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: 'New PR to hoge branch'
        pr_body: 'Automatic PR creation to hoge branch'
        destination_branch: 'main'